import videoLibrary from '../assets/video-library.png'
import Ecom from '../assets/E-com.png'
import weather from '../assets/weather.png'
import musicPlayer from '../assets/music-player.png'
import tringle from '../assets/tringle.webp'
import lucky from '../assets/Lucky.jpg'
import palindeom from '../assets/palindeom.webp'
import component from '../assets/component.png'
import spotify from '../assets/spotify.png'
const projects = [
    {
        id: 'pro1',
        url: videoLibrary,
        title: 'A|R-video-library',
        desc: "This video library in made in react with some of the awesome features.",
        github: 'https://github.com/AlligatorrA/ar-video-library.git',
        live: 'https://ar-video-library.netlify.app/',
    },
    {
        id: 'pro2',
        url: Ecom,
        title: 'A|R e-commerce',
        desc: "This project is made using react with awsome feature using react components.",
        github: 'https://github.com/AlligatorrA/e-commerce-React.git',
        live: 'https://alli-ar-ecom.netlify.app',
    },
    {
        id: 'pro3',
        url: weather,
        title: 'weather-app',
        desc: "Tells the current weather, temp and date with random quotes and random images",
        github: 'https://github.com/AlligatorrA/weather-app.git',
        live: 'https://weather-app-two-gold.vercel.app/',
    },
    {
        id: 'pro4',
        url: component,
        title: 'Comoponent-library',
        desc: "Components library with Badges, Avtar, alert,round-img Card,modals form etc...",
        github: 'https://github.com/AlligatorrA/weather-app.git',
        live: 'https://alli-dark-component-library.netlify.app/',
    },
    {
        id: 'pro5',
        url: musicPlayer,
        title: 'music player',
        desc: "music player UI/UX design in react js users friendly and resposive",
        github: 'https://github.com/AlligatorrA/music-app.git',
        live: 'https://ar-music-app.netlify.app/',
    },
    {
        id: 'pro6',
        url: spotify,
        title: 'Spotify clone UI',
        desc: "Spotify clone UI design with Html CSS and js",
        github: 'https://github.com/AlligatorrA/Spotify.git',
        live: 'https://spotify-clone-alli.netlify.app/',
    },
    {
        id: 'pro7',
        url: musicPlayer,
        title: 'Twitter clone UI',
        desc: "Twitter clone UI design with Html CSS and js",
        github: 'https://github.com/AlligatorrA/Twitter-UI.git',
        live: 'https://allitwitterui.netlify.app/',
    },
    {
        id: 'pro8',
        url: tringle,
        title: 'fun with Triangle',
        desc: "This is a  Triangle app it can calculate area and it has a quiz part too lets see how much you know of triangle.",
        github: 'https://github.com/AlligatorrA/Fun-with-Tringle.git',
        live: 'https://allifunwithtringle.netlify.app//',
    },
    {
        id: 'pro9',
        url: musicPlayer,
        title: 'Cash Register',
        desc: "This is a cash register manager. It indicates the money needed to be returned. buit-in javaScript.",
        github: 'https://github.com/AlligatorrA/Cash-Register-Manager.git',
        live: 'https://allicashmanager.netlify.app/',
    },
    {
        id: 'pro10',
        url: palindeom,
        title: 'Birthday Palindrome or not',
        desc: "This App will tell you whether you birtdate is palindrome or not along with the closer palindrome date to your birthday.",
        github: 'https://github.com/AlligatorrA/Birthday-Palindrome.git ',
        live: 'https://birthday-palindrome.alligatorr.repl.co/',
    },
    {
        id: 'pro11',
        url: musicPlayer,
        title: 'Profit and loss',
        desc: "This app tells you how much profit or loss you have made along with percentage based on current price, number of Products and its purchase price.",
        github: 'https://github.com/AlligatorrA/ProfitAndLoss.git',
        live: 'https://alliprofitloss.netlify.app/',
    },
    {
        id: 'pro12',
        url: musicPlayer,
        title: 'The Originals Fan Game',
        desc: "This quiz is for `The Originals` webseries fan if you are fan of the great evil `klaus Mikealson` .  Built-in NodeJs.",
        github: 'https://github.com/AlligatorrA/TheOriginalsFansGame.git',
        live: 'https://replit.com/@Alligatorr/TheOriginalsFansGame?embed=1&output=1#index.js',
    },
    {
        id: 'pro13',
        url: musicPlayer,
        title: 'Favourite Webseries',
        desc: "List of Webseries.Webseries You Should Watch if you are fan of Action or Bio-World or Science-Fiction. Built-in React js.",
        github: 'https://github.com/AlligatorrA/Fav-Webseries.git',
        live: 'https://fav-webseries.netlify.app',
    },
    {
        id: 'pro14',
        url: musicPlayer,
        title: 'Good Books',
        desc: "Books you Should read If you are fan of Thrill or Biotechnology or Action. Built using HTML, CSS and React js.",
        github: 'https://github.com/AlligatorrA/GoodBooks.git',
        live: 'https://allligoodbooks.netlify.app/',
    },
    {
        id: 'pro15',
        url: lucky,
        title: 'Birthday Lucky-or-Not',
        desc: "Lets Play this game Your Birthday Lucky or Not. Built-in pure javaScript.",
        github: 'https://github.com/AlligatorrA/Birthday-lucky-or-not.git',
        live: 'https://birthday-lucky-or-not.alligatorr.repl.co/',
    },
    {
        id: 'pro16',
        url: musicPlayer,
        title: 'Emoji Dictionary',
        desc: "Try this Emoji Dictionary. It returns the Meaning of Emoji. Built-in React js. ",
        github: 'https://github.com/AlligatorrA/csb-iwxwv.git',
        live: 'https://czbz2.csb.app/',
    },
    {
        id: 'pro17',
        url: musicPlayer,
        title: 'Talk British',
        desc: "Are you fan of British accent? Try this App and learn how to speak British. Built-in vanilla js.",
        github: 'https://github.com/AlligatorrA/Talk-British.git',
        live: 'https://talkbritishbyanand.netlify.app/',
    },
    {
        id: 'pro18',
        url: musicPlayer,
        title: 'Banana Talk',
        desc: "Try this Banana Talk App. It returns the language in Banana. Built-in javaScript.",
        github: 'https://github.com/AlligatorrA/Banana-speak.git',
        live: 'https://quirky-panini-banana.netlify.app',
    },
    {
        id: 'pro19',
        url: musicPlayer,
        title: 'How Much you know me',
        desc: "How much you know me. Built-in NodeJs.",
        github: 'https://github.com/AlligatorrA/end-game.git',
        live: 'https://replit.com/@Alligatorr/end-game?embed=1&output=1#index.js',
    },
];
export { projects }